language: node_js

nod_js:
    - 'stable'

sudo: false

before_install:
- openssl aes-256-cbc -K $encrypted_a86616fdbe0b_key -iv $encrypted_a86616fdbe0b_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'AndKid'
- git config --global user.email cygcloud@163.com
- git clone -b master git@github.com:AndKid/andkid.github.io.git .deploy_git

install:
#安装更新的一个软件
- npm install n -g
#更新到最新stable版本
- n stable
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g
- hexo d

branches:
  only:
  - blog
